"""seguridad login: bloqueo por intentos y codigos de verificacion

Revision ID: 70654008bd0e
Revises: 2cb9737f85d2
Create Date: 2026-08-30 23:07:06.945995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70654008bd0e'
down_revision: Union[str, None] = '2cb9737f85d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN_2FA', 'PASSWORD_RESET', name='auth_code_purpose'), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_codes_id'), 'auth_codes', ['id'], unique=False)
    op.create_index(op.f('ix_auth_codes_user_id'), 'auth_codes', ['user_id'], unique=False)
    # NOTA: 'spatial_ref_sys' es una tabla interna de PostGIS (no del modelo de
    # datos de RUTIA); el autogenerate de Alembic la marca como "sobrante"
    # porque no está en nuestros modelos, pero borrarla rompería PostGIS. Se
    # quitó ese `op.drop_table('spatial_ref_sys')` a propósito.
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_auth_codes_user_id'), table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_id'), table_name='auth_codes')
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
